<x-layout.app title="Warehouses | Express Cloud">
    <x-layout.app-shell page-title="Warehouses and stock control" page-description="Warehouse-specific available, reserved, quarantine and damaged stock with append-only movements.">
        <form method="GET" class="mb-5 flex gap-3 rounded-xl border bg-white p-4"><select name="warehouse_id" class="min-h-11 flex-1 rounded-lg border px-3"><option value="">All warehouses</option>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}" @selected($warehouseId===(string)$warehouse->id)>{{ $warehouse->name }} · {{ $warehouse->branch?->name }}</option>@endforeach</select><x-ui.button type="submit">Filter</x-ui.button></form>

        <div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_430px]">
            <x-ui.card title="Warehouse balances">
                <div class="overflow-x-auto"><table class="w-full min-w-[850px] text-sm"><thead><tr class="border-b text-left text-xs uppercase text-slate-500"><th class="p-3">Warehouse</th><th class="p-3">Product</th><th class="p-3">Condition</th><th class="p-3 text-right">Quantity</th><th class="p-3 text-right">Reserved</th><th class="p-3 text-right">Value</th></tr></thead><tbody>@forelse($balances as $balance)<tr class="border-b"><td class="p-3">{{ $balance->warehouse?->name }}</td><td class="p-3"><strong>{{ $balance->product?->name }}</strong><div class="font-mono text-xs text-slate-500">{{ $balance->product?->sku }}</div></td><td class="p-3">{{ ucfirst($balance->condition) }}</td><td class="p-3 text-right">{{ number_format($balance->quantity_milliunits/1000,3) }}</td><td class="p-3 text-right">{{ number_format($balance->reserved_milliunits/1000,3) }}</td><td class="p-3 text-right">₦{{ number_format($balance->inventory_value_kobo/100,2) }}</td></tr>@empty<tr><td colspan="6" class="p-10 text-center text-slate-500">No warehouse balances.</td></tr>@endforelse</tbody></table></div>{{ $balances->links() }}
            </x-ui.card>

            <div class="space-y-6">
                <x-ui.card title="Create warehouse"><form method="POST" action="{{ route('admin.warehouses.store') }}" class="space-y-3">@csrf<input type="hidden" name="idempotency_key" value="{{ (string) \Illuminate\Support\Str::ulid() }}"><select name="branch_id" required class="min-h-11 w-full rounded-lg border px-3"><option value="">Branch</option>@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->name }}</option>@endforeach</select><x-ui.input name="code" label="Code" required /><x-ui.input name="name" label="Name" required /><select name="type" class="min-h-11 w-full rounded-lg border px-3"><option value="warehouse">Warehouse</option><option value="store">Store</option><option value="transit">Transit</option><option value="quarantine">Quarantine</option></select><label class="flex gap-2 text-sm"><input type="checkbox" name="allows_receipts" value="1" checked>Allow receipts</label><label class="flex gap-2 text-sm"><input type="checkbox" name="allows_sales" value="1">Allow sales</label><label class="flex gap-2 text-sm"><input type="checkbox" name="is_default" value="1">Default for branch</label><x-ui.button type="submit" class="w-full">Create warehouse</x-ui.button></form></x-ui.card>

                <x-ui.card title="Warehouse transfer"><form method="POST" action="{{ route('admin.warehouses.transfer') }}" class="space-y-3">@csrf<input type="hidden" name="idempotency_key" value="{{ (string) \Illuminate\Support\Str::ulid() }}"><select name="product_id" required class="min-h-11 w-full rounded-lg border px-3"><option value="">Product</option>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->name }} · {{ $product->sku }}</option>@endforeach</select><select name="source_warehouse_id" required class="min-h-11 w-full rounded-lg border px-3"><option value="">Source</option>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}">{{ $warehouse->name }}</option>@endforeach</select><select name="destination_warehouse_id" required class="min-h-11 w-full rounded-lg border px-3"><option value="">Destination</option>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}">{{ $warehouse->name }}</option>@endforeach</select><x-ui.input name="quantity" label="Quantity" required /><select name="condition" class="min-h-11 w-full rounded-lg border px-3"><option value="available">Available</option><option value="quarantine">Quarantine</option><option value="damaged">Damaged</option></select><x-ui.input name="note" label="Note" /><x-ui.button type="submit" class="w-full">Transfer stock</x-ui.button></form></x-ui.card>

                <x-ui.card title="Reserve stock"><form method="POST" action="{{ route('admin.warehouses.reserve') }}" class="space-y-3">@csrf<input type="hidden" name="idempotency_key" value="{{ (string) \Illuminate\Support\Str::ulid() }}"><select name="warehouse_id" required class="min-h-11 w-full rounded-lg border px-3"><option value="">Warehouse</option>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}">{{ $warehouse->name }}</option>@endforeach</select><select name="product_id" required class="min-h-11 w-full rounded-lg border px-3"><option value="">Product</option>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->name }}</option>@endforeach</select><x-ui.input name="quantity" label="Quantity" required /><x-ui.input name="reference_type" label="Reference type" value="sales_order" required /><x-ui.input name="reference_id" label="Reference ID" required /><x-ui.input name="expires_at" type="datetime-local" label="Expires at" /><x-ui.button type="submit" class="w-full">Reserve</x-ui.button></form></x-ui.card>

                <x-ui.card title="Physical count"><form method="POST" action="{{ route('admin.warehouses.count') }}" class="space-y-3">@csrf<input type="hidden" name="idempotency_key" value="{{ (string) \Illuminate\Support\Str::ulid() }}"><select name="warehouse_id" required class="min-h-11 w-full rounded-lg border px-3"><option value="">Warehouse</option>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}">{{ $warehouse->name }}</option>@endforeach</select><select name="product_id" required class="min-h-11 w-full rounded-lg border px-3"><option value="">Product</option>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->name }}</option>@endforeach</select><x-ui.input name="counted_quantity" label="Counted quantity" required /><select name="condition" class="min-h-11 w-full rounded-lg border px-3"><option value="available">Available</option><option value="quarantine">Quarantine</option><option value="damaged">Damaged</option></select><x-ui.input name="notes" label="Notes" /><x-ui.button type="submit" class="w-full">Post count</x-ui.button></form></x-ui.card>
            </div>
        </div>
    </x-layout.app-shell>
</x-layout.app>
