<x-layout.app title="Change Approvals | Express Cloud">
    <x-layout.app-shell page-title="Maker-checker administration" page-description="Sensitive branch, warehouse, customer, payment-method, department and employee changes require an independent decision.">
        <div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_420px]">
            <x-ui.card title="Administrative change queue">
                <div class="overflow-x-auto"><table class="w-full min-w-[900px] text-sm"><thead><tr class="border-b text-left text-xs uppercase text-slate-500"><th class="p-3">Resource</th><th class="p-3">Action</th><th class="p-3">Status</th><th class="p-3">Memo</th><th class="p-3">Decision</th></tr></thead><tbody>@forelse($requests as $change)<tr class="border-b align-top"><td class="p-3"><strong>{{ class_basename($change->resource_type) }}</strong><div class="font-mono text-xs text-slate-500">{{ $change->resource_id }}</div></td><td class="p-3">{{ ucfirst($change->action) }}</td><td class="p-3">{{ ucfirst($change->status) }}</td><td class="p-3 max-w-sm whitespace-normal">{{ $change->business_memo }}</td><td class="p-3">@if($change->status==='pending')<form method="POST" action="{{ route('admin.governance.changes.decide', $change) }}" class="grid gap-2">@csrf<select name="decision" class="min-h-9 rounded border px-2"><option value="approve">Approve</option><option value="reject">Reject</option></select><input name="note" required placeholder="Independent decision note" class="min-h-9 rounded border px-2"><button class="min-h-9 rounded bg-slate-900 px-3 text-xs font-semibold text-white">Record decision</button></form>@else<span class="text-xs text-slate-500">{{ $change->decision_note }}</span>@endif</td></tr>@empty<tr><td colspan="5" class="p-10 text-center text-slate-500">No change requests.</td></tr>@endforelse</tbody></table></div>
                @if($requests->hasPages())<div class="border-t p-4">{{ $requests->links() }}</div>@endif
            </x-ui.card>
            <x-ui.card title="Submit controlled change"><form method="POST" action="{{ route('admin.governance.changes.store') }}" class="space-y-3">@csrf<select name="resource" class="min-h-11 w-full rounded-lg border px-3">@foreach($resources as $resource)<option value="{{ $resource }}">{{ ucfirst(str_replace('_',' ',$resource)) }}</option>@endforeach</select><select name="action" class="min-h-11 w-full rounded-lg border px-3"><option value="update">Update</option><option value="create">Create</option><option value="deactivate">Deactivate</option><option value="reactivate">Reactivate</option></select><x-ui.input name="resource_id" label="Resource ULID (for existing records)" /><x-ui.input name="payload[name]" label="Proposed name/value" /><x-ui.input name="memo" label="Required business memo" required /><x-ui.button type="submit" class="w-full">Submit for approval</x-ui.button></form></x-ui.card>
        </div>
    </x-layout.app-shell>
</x-layout.app>
