<x-layout.app title="Enterprise Procurement | Express Cloud">
    <x-layout.app-shell page-title="Requisitions, receipts and landed cost" page-description="Approval-led procurement with partial receipts, backorders, quarantine and inventory capitalization.">
        <div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_430px]">
            <div class="space-y-6">
                <x-ui.card title="Purchase requisitions">
                    <div class="overflow-x-auto"><table class="w-full min-w-[760px] text-sm"><thead><tr class="border-b text-left text-xs uppercase text-slate-500"><th class="p-3">Number</th><th class="p-3">Warehouse</th><th class="p-3">Status</th><th class="p-3">Priority</th><th class="p-3">Actions</th></tr></thead><tbody>@forelse($requisitions as $requisition)<tr class="border-b"><td class="p-3 font-mono">{{ $requisition->requisition_number }}</td><td class="p-3">{{ $requisition->warehouse?->name }}</td><td class="p-3">{{ ucfirst($requisition->status) }}</td><td class="p-3">{{ ucfirst($requisition->priority) }}</td><td class="p-3"><div class="flex flex-wrap gap-2">@if($requisition->status==='submitted')<form method="POST" action="{{ route('admin.procurement.enterprise.requisitions.approve',$requisition) }}">@csrf<input type="hidden" name="idempotency_key" value="{{ (string) \Illuminate\Support\Str::ulid() }}"><x-ui.button type="submit">Approve</x-ui.button></form>@endif @if($requisition->status==='approved')<form method="POST" action="{{ route('admin.procurement.enterprise.requisitions.convert',$requisition) }}" class="flex gap-2">@csrf<input type="hidden" name="idempotency_key" value="{{ (string) \Illuminate\Support\Str::ulid() }}"><select name="supplier_id" required class="min-h-10 rounded-lg border px-2"><option value="">Supplier</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}">{{ $supplier->company_name }}</option>@endforeach</select><x-ui.button type="submit">Create PO</x-ui.button></form>@endif</div></td></tr>@empty<tr><td colspan="5" class="p-8 text-center text-slate-500">No requisitions.</td></tr>@endforelse</tbody></table></div>{{ $requisitions->links() }}
                </x-ui.card>

                <x-ui.card title="Open purchase orders and backorders">
                    <div class="space-y-3">@forelse($orders as $order)<details class="rounded-lg border p-4"><summary class="cursor-pointer font-semibold">{{ $order->order_number }} · {{ $order->supplier?->company_name }} · {{ $order->status instanceof \BackedEnum ? $order->status->value : $order->status }}</summary><div class="mt-4 space-y-3">@foreach($order->lines as $line)<form method="POST" action="{{ route('admin.procurement.enterprise.orders.receive',$order) }}" class="grid gap-2 rounded-lg bg-slate-50 p-3 md:grid-cols-4">@csrf<input type="hidden" name="idempotency_key" value="{{ (string) \Illuminate\Support\Str::ulid() }}"><input type="hidden" name="line_id" value="{{ $line->id }}"><select name="warehouse_id" required class="min-h-10 rounded-lg border px-2">@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}" @selected((string)$order->warehouse_id===(string)$warehouse->id)>{{ $warehouse->name }}</option>@endforeach</select><x-ui.input name="quantity" label="Received" :value="number_format($line->remainingMilliunits()/1000,3,'.','')" required /><x-ui.input name="accepted_quantity" label="Accepted" :value="number_format($line->remainingMilliunits()/1000,3,'.','')" /><x-ui.input name="quarantine_quantity" label="Quarantine" value="0" /><x-ui.input name="batch_number" label="Batch" /><x-ui.input name="expires_on" type="date" label="Expiry" /><x-ui.button type="submit">Post receipt</x-ui.button></form>@endforeach</div></details>@empty<p class="text-sm text-slate-500">No purchase orders.</p>@endforelse</div>
                </x-ui.card>

                <x-ui.card title="Goods receipts and landed cost">
                    <div class="space-y-3">@forelse($receipts as $receipt)<form method="POST" action="{{ route('admin.procurement.enterprise.receipts.landed-cost',$receipt) }}" class="grid gap-2 rounded-lg border p-3 md:grid-cols-4">@csrf<input type="hidden" name="idempotency_key" value="{{ (string) \Illuminate\Support\Str::ulid() }}"><div><p class="font-semibold">{{ $receipt->receipt_number }}</p><p class="text-xs text-slate-500">{{ $receipt->purchaseOrder?->order_number }} · {{ $receipt->warehouse?->name }}</p></div><x-ui.input name="description" label="Cost description" required /><x-ui.input name="amount" type="number" step="0.01" label="Amount" required /><select name="allocation_method" class="min-h-11 self-end rounded-lg border px-3"><option value="value">By value</option><option value="quantity">By quantity</option><option value="equal">Equal</option></select><x-ui.button type="submit">Allocate landed cost</x-ui.button></form>@empty<p class="text-sm text-slate-500">No goods receipts.</p>@endforelse</div>
                </x-ui.card>
            </div>

            <x-ui.card title="New purchase requisition">
                <form method="POST" action="{{ route('admin.procurement.enterprise.requisitions.store') }}" class="space-y-3">@csrf<input type="hidden" name="idempotency_key" value="{{ (string) \Illuminate\Support\Str::ulid() }}">
                    <select name="warehouse_id" required class="min-h-11 w-full rounded-lg border px-3"><option value="">Destination warehouse</option>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}">{{ $warehouse->name }}</option>@endforeach</select>
                    <select name="product_id" required class="min-h-11 w-full rounded-lg border px-3"><option value="">Product</option>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->name }} · {{ $product->sku }}</option>@endforeach</select>
                    <x-ui.input name="quantity" label="Requested quantity" required />
                    <x-ui.input name="estimated_unit_cost" type="number" step="0.01" label="Estimated unit cost" />
                    <select name="priority" class="min-h-11 w-full rounded-lg border px-3"><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option><option value="low">Low</option></select>
                    <x-ui.input name="needed_on" type="date" label="Needed on" />
                    <label class="block"><span class="mb-2 block text-sm font-medium">Reason</span><textarea name="reason" required class="min-h-28 w-full rounded-lg border p-3"></textarea></label>
                    <x-ui.button type="submit" class="w-full">Submit requisition</x-ui.button>
                </form>
            </x-ui.card>
        </div>
    </x-layout.app-shell>
</x-layout.app>
