<x-layout.app title="HR Administration | Express Cloud">
    <x-layout.app-shell page-title="HR and workforce administration" page-description="Departments, employee profiles, assignments, attendance, holidays, performance and payroll-ready controls.">
        <div class="grid gap-6 xl:grid-cols-[minmax(0,1.4fr)_430px]">
            <div class="space-y-6">
                <x-ui.card title="Employee register">
                    <div class="overflow-x-auto"><table class="w-full min-w-[800px] text-sm"><thead><tr class="border-b text-left text-xs uppercase text-slate-500"><th class="p-3">Employee</th><th class="p-3">Code</th><th class="p-3">Employment</th><th class="p-3">Status</th><th class="p-3">Assignment</th></tr></thead><tbody>@forelse($employees as $employee)<tr class="border-b"><td class="p-3 font-semibold">{{ $employee->displayName() }}</td><td class="p-3 font-mono text-xs">{{ $employee->employee_code }}</td><td class="p-3">{{ str_replace('_',' ',$employee->employment_type) }}</td><td class="p-3">{{ ucfirst($employee->status) }}</td><td class="p-3"><form method="POST" action="{{ route('admin.hr.employees.assign', $employee) }}" class="flex flex-wrap gap-2">@csrf<input type="date" name="starts_on" value="{{ now()->toDateString() }}" class="rounded border px-2"><select name="department_id" class="rounded border px-2"><option value="">Department</option>@foreach($departments as $department)<option value="{{ $department->id }}">{{ $department->name }}</option>@endforeach</select><input name="memo" required placeholder="Assignment memo" class="rounded border px-2"><button class="rounded bg-slate-900 px-3 text-xs font-semibold text-white">Assign</button></form></td></tr>@empty<tr><td colspan="5" class="p-10 text-center text-slate-500">No employees.</td></tr>@endforelse</tbody></table></div>
                    @if($employees->hasPages())<div class="border-t p-4">{{ $employees->links() }}</div>@endif
                </x-ui.card>
                <div class="grid gap-6 lg:grid-cols-2"><x-ui.card title="Recent attendance"><div class="space-y-2">@forelse($attendance as $row)<div class="rounded border p-3 text-sm"><strong>{{ $row->employee_id }}</strong><div>{{ $row->work_date?->format('d M Y') }} · {{ ucfirst($row->status) }} · {{ $row->worked_minutes }} min</div></div>@empty<p class="text-sm text-slate-500">No attendance records.</p>@endforelse</div></x-ui.card><x-ui.card title="Holiday calendar"><div class="space-y-2">@forelse($holidays as $holiday)<div class="rounded border p-3 text-sm"><strong>{{ $holiday->name }}</strong><div>{{ $holiday->holiday_date?->format('d M Y') }}</div></div>@empty<p class="text-sm text-slate-500">No holidays configured.</p>@endforelse</div></x-ui.card></div>
            </div>
            <div class="space-y-6">
                <x-ui.card title="Create employee"><form method="POST" action="{{ route('admin.hr.employees.store') }}" class="space-y-3">@csrf<input type="hidden" name="idempotency_key" value="{{ (string) \Illuminate\Support\Str::ulid() }}"><x-ui.input name="first_name" label="First name" required /><x-ui.input name="last_name" label="Last name" required /><x-ui.input name="employee_code" label="Employee code (optional)" /><x-ui.input name="phone" label="Phone" /><select name="branch_id" class="min-h-11 w-full rounded-lg border px-3"><option value="">Branch</option>@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->name }}</option>@endforeach</select><select name="department_id" class="min-h-11 w-full rounded-lg border px-3"><option value="">Department</option>@foreach($departments as $department)<option value="{{ $department->id }}">{{ $department->name }}</option>@endforeach</select><select name="job_role_id" class="min-h-11 w-full rounded-lg border px-3"><option value="">Job role</option>@foreach($roles as $role)<option value="{{ $role->id }}">{{ $role->title }}</option>@endforeach</select><select name="employment_type" class="min-h-11 w-full rounded-lg border px-3"><option value="full_time">Full time</option><option value="part_time">Part time</option><option value="contract">Contract</option><option value="temporary">Temporary</option><option value="intern">Intern</option></select><x-ui.button type="submit" class="w-full">Create employee</x-ui.button></form></x-ui.card>
                <x-ui.card title="Add holiday"><form method="POST" action="{{ route('admin.hr.holidays.store') }}" class="space-y-3">@csrf<x-ui.input name="name" label="Holiday name" required /><x-ui.input name="holiday_date" type="date" label="Date" required /><select name="branch_id" class="min-h-11 w-full rounded-lg border px-3"><option value="">All branches</option>@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->name }}</option>@endforeach</select><label class="flex gap-2 text-sm"><input type="checkbox" name="is_paid" value="1" checked>Paid holiday</label><x-ui.button type="submit" class="w-full">Save holiday</x-ui.button></form></x-ui.card>
                <x-ui.card title="Payroll control"><p class="text-sm text-slate-500">Payroll remains disabled unless statutory settings are deliberately enabled through <code>HR_PAYROLL_ENABLED=true</code>. Draft runs cannot bypass maker-checker approval.</p></x-ui.card>
            </div>
        </div>
    </x-layout.app-shell>
</x-layout.app>
