<x-layout.app title="Lisa AI | Express Cloud"><x-layout.app-shell page-title="Lisa AI" page-description="Role-aware analytics, business guidance and application documentation.">
<div class="grid gap-5 lg:grid-cols-[300px_minmax(0,1fr)]"><aside class="rounded-2xl border bg-white p-4">
<form method="POST" action="{{ route('admin.insights.chat.store') }}">@csrf<button class="min-h-11 w-full rounded-xl bg-slate-950 px-4 font-semibold text-white">New chat</button></form>
<form class="mt-4"><input name="search" value="{{ request('search') }}" placeholder="Search your chats" class="min-h-11 w-full rounded-xl border px-3"></form>
<div class="mt-4 space-y-2">@foreach($conversations as $conversation)<a href="{{ route('admin.insights.chat.show',$conversation) }}" class="block rounded-xl border p-3 hover:bg-slate-50"><b class="block truncate">{{ $conversation->title }}</b><small>{{ optional($conversation->last_message_at)->diffForHumans() }}</small></a>@endforeach</div><div class="mt-4">{{ $conversations->links() }}</div></aside>
<section class="flex min-h-[68vh] flex-col overflow-hidden rounded-2xl border bg-white" @if($activeConversation) x-data="lisaChat('{{ route('admin.insights.chat.message',$activeConversation) }}','{{ csrf_token() }}')" @endif>
@if(!$activeConversation)<div class="grid flex-1 place-items-center p-8 text-center"><div><div class="mx-auto grid h-20 w-20 place-items-center rounded-full bg-blue-50 text-4xl">😉</div><h2 class="mt-5 text-2xl font-bold">Hello, {{ auth()->user()->first_name ?? 'there' }}</h2><p class="mt-2 text-slate-600">Ask about authorised business data or how to use any Express Cloud workflow.</p></div></div>
@else<header class="border-b px-5 py-4"><h2 class="font-bold">{{ $activeConversation->title }}</h2><p class="text-xs text-slate-500">Chat history is retained and cannot be deleted by users.</p></header>
<div class="flex-1 space-y-4 overflow-y-auto p-5" x-ref="messages">@foreach($activeConversation->messages as $m)<div class="max-w-[85%] rounded-2xl px-4 py-3 text-sm {{ $m->role==='user'?'ml-auto bg-slate-950 text-white':'mr-auto bg-slate-100' }}">{{ $m->content }}</div>@endforeach<template x-for="m in messages" :key="m.id"><div class="max-w-[85%] rounded-2xl px-4 py-3 text-sm" :class="m.role==='user'?'ml-auto bg-slate-950 text-white':'mr-auto bg-slate-100'" x-text="m.content"></div></template><div x-show="typing" class="mr-auto rounded-2xl bg-slate-100 px-4 py-3">Lisa is typing<span class="animate-pulse">...</span></div></div>
<form class="border-t p-4" x-on:submit.prevent="send"><div class="flex gap-3"><textarea x-model="draft" rows="2" placeholder="Ask Lisa" class="flex-1 rounded-xl border p-3"></textarea><button :disabled="sending||!draft.trim()" class="self-end rounded-xl bg-blue-700 px-5 py-3 font-semibold text-white">Send</button></div></form>@endif</section></div>
<script>function lisaChat(endpoint,csrf){return{draft:'',sending:false,typing:false,messages:[],async send(){const c=this.draft.trim();if(!c||this.sending)return;this.messages.push({id:crypto.randomUUID(),role:'user',content:c});this.draft='';this.sending=true;this.typing=true;try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':csrf},body:JSON.stringify({message:c})});const p=await r.json();if(!r.ok)throw new Error(p.message||'Lisa could not respond.');await new Promise(x=>setTimeout(x,450));this.messages.push({id:crypto.randomUUID(),role:'assistant',content:p.reply});}catch(e){this.messages.push({id:crypto.randomUUID(),role:'assistant',content:e.message});}finally{this.typing=false;this.sending=false;this.$nextTick(()=>this.$refs.messages.scrollTop=this.$refs.messages.scrollHeight)}}}}</script>
</x-layout.app-shell></x-layout.app>
